src/Entity/VinylMix.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use App\Repository\VinylMixRepository;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: VinylMixRepository::class)]
class VinylMix
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $trackCount = null;

    #[ORM\Column(length: 255)]
    private ?string $genre = null;

    #[ORM\Column]
    // private \DateTimeImmutable $createdAt;

    //#[ORM\Column]
    private int $votes = 0;
    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['title'])]
    private ?string $slug = null;
    /* public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }*/

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getTrackCount(): ?int
    {
        return $this->trackCount;
    }

    public function setTrackCount(int $trackCount): static
    {
        $this->trackCount = $trackCount;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }



    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): static
    {
        $this->votes = $votes;

        return $this;
    }
    public function upVote(): void
    {
        $this->votes++;
    }
    public function downVote(): void
    {
        $this->votes--;
    }
    public function getVotesString(): String
    {
        $prefix = ($this->votes === 0) ? '' : (($this->votes >= 0) ? '+' : '-');
        return sprintf('%s %d', $prefix, abs($this->votes));
    }
    public function getImageUrl(int $width): string
    {
        return sprintf(
            'https://picsum.photos/id/%d/%d',
            ($this->getId() + 50) % 1000, // number between 0 and 1000, based on the id
            $width
        );
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }
}

templates/mix/_recordSvg.html.twig
<svg width="100%" height="100%" viewBox="0 0 496 496" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
            <stop stop-color="#C380F3" offset="0%"></stop>
            <stop stop-color="#4A90E2" offset="100%"></stop>
        </linearGradient>
    </defs>
    <g id="Mixed-Vinyl" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Group">
            <g id="record-vinyl" fill="#000000" fill-rule="nonzero">
                <path d="M248,144 C190.562386,144 144,190.562386 144,248 C144,305.437614 190.562386,352 248,352 C305.437614,352 352,305.437614 352,248 C352,190.562386 305.437614,144 248,144 L248,144 Z M248,272 C234.745166,272 224,261.254834 224,248 C224,234.745166 234.745166,224 248,224 C261.254834,224 272,234.745166 272,248 C272,261.254834 261.254834,272 248,272 Z M248,0 C111,0 0,111 0,248 C0,385 111,496 248,496 C385,496 496,385 496,248 C496,111 385,0 248,0 Z M248,376 C177.307552,376 120,318.692448 120,248 C120,177.307552 177.307552,120 248,120 C318.692448,120 376,177.307552 376,248 C376,281.947711 362.514324,314.505012 338.509668,338.509668 C314.505012,362.514324 281.947711,376 248,376 Z" id="Shape"></path>
            </g>
            <g id="record-vinyl" transform="translate(144.000000, 144.000000)" fill="url(#linearGradient-1)" fill-rule="nonzero">
                <path d="M104,0 C46.562386,0 0,46.562386 0,104 C0,161.437614 46.562386,208 104,208 C161.437614,208 208,161.437614 208,104 C208,46.562386 161.437614,0 104,0 L104,0 Z M104,128 C90.745166,128 80,117.254834 80,104 C80,90.745166 90.745166,80 104,80 C117.254834,80 128,90.745166 128,104 C128,117.254834 117.254834,128 104,128 Z" id="Shape"></path>
            </g>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="235"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="215"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="195"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="175"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="155"></circle>
        </g>
    </g>
</svg>

templates/mix/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	{{ mix.title }}
	Mix
{% endblock %}
{% block body %}
	<div class="container">
		<h1 class="d-inline me-3">{{ mix.title }}</h1>

		<div class="row mt-5">
			<div class="col-12 col-md-4">
				{{ include('mix/_recordSvg.html.twig') }}
			</div>

			<div class="col-12 col-md-8 ps-5">
				<h2 class="mb-4">{{ mix.trackCount }}
					songs
					<small>(genre:
						{{ mix.genre }})</small>
				</h2>
				<p>{{ mix.description }}</p>
				{{ mix.votesString }}
				votes
				<form action="{{ path('app_mix_vote', {id: mix.id }) }}" method="POST">
					<button type="submit" name="direction" value="up" class="btn btn-outline-primary">
						<span class="fa fa-thumbs-up"></span>
					</button>
					<button type="submit" class="btn btn-outline-primary" name="direction" value="down">
						<span class="fa fa-thumbs-down"></span>
					</button>
				</form>
			</form>
		</div>
	</div>
</div>{% endblock %}